### ISSUE TITLE
Add more detailed README for step by step instructions on how to run this backend

### ISSUE THREAD

**Issue by shipsywor** [uzaysan/social-app-backend#1]
The current README shows configurations steps, but how do we run the backend, etc.

Coming from the android repo, it would be great to add more detailed README for step by step instructions on how to run this backend.

Make it more beginner friendly with added screenshots of steps involved to get this backend running. So that its easier to work with android app.

**Comment by uzaysan** [comment]
I can make a script to run this backend. And It will take care of it? Does it sound good? Yet still there may be some steps you have to do on database level. I can add steps for that too.

**Comment by shipsywor** [comment]
Seeing the edited comment, yes more detailed README is always better as the steps by step setup of the backend won't be hidden behind script that just works magically.

Thank you. Please include instructions, hoping to try out this backend and connect with android app.

Also, if there are any gotchas or special steps needed to make Android app work with the backend, add that as well. Or if it just adding localhost:8000 to baseurl or something, please mention that as well.

Thank you, I am asking a lot.

**Comment by uzaysan** [comment]
@shipsywor I've edited readme.

**Comment by shipsywor** [comment]
Thank you. I will update the issue and let you know when I try running the backend.
